version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    ports:
      - "127.0.0.1:4533:4533"
    restart: unless-stopped
    environment:
      # https://www.navidrome.org/docs/usage/configuration-options/#enviroment-variables
      ND_SCANINTERVAL: 1m
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 30m
      ND_BASEURL: ""
    volumes:
      - "/var/lib/navidrome/data:/data"
      - "/data/music:/music:ro"