version: "3"
services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: netdata.example.com # set to fqdn of host
    ports:
      - 127.0.0.1:19999:19999
    environment:
      - DO_NOT_TRACK=1
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /etc/netdata/netdata.conf:/etc/netdata/netdata.conf:ro
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro

volumes:
  netdatalib:
  netdatacache: