---
- hosts: all
  tasks:
  - name: Create temporary download directory
    tempfile:
      state: directory
    register: tempdir

  - name: Download Caddy Debian package from official GitHub Page
    get_url:
      # Debian package of Caddy 2.2.1 for Linux amd64
      url: https://github.com/caddyserver/caddy/releases/download/v2.2.1/caddy_2.2.1_linux_amd64.deb
      dest: "{{ tempdir.path }}/caddy.deb"
      # SHA-512 sum of the Debian package from the cheksums file of the GitHub release page
      checksum: sha512:8160b2a886daef3bdb8166cf7328c19068e87b605b8d724ff424f4c3b2cf7bc96db0eec88ac3a9cbf473206d2441cfa37e4be6c8b5f9cd255650e83e1702b4df

  - name: Install Caddy Debian package
    apt:
      deb: "{{ tempdir.path }}/caddy.deb"
    become: yes
    register: deb_install_status
    # Execute the task only on Debian-based hosts
    when: ansible_facts['os_family'] == "Debian"

  - name: Remove the temporary directory
    file:
      path: "{{ tempdir.path }}"
      state: absent
    when: tempdir.path is defined

  - name: Create caddy directory, if it does not exist
    file:
      path: /etc/caddy
      state: directory
      owner: root
      group: root
      mode: '0755'
    become: yes

  - name: Copy provided Caddyfile example
    copy:
      dest: /etc/caddy/Caddyfile
      src: ../software/caddy/Caddyfile
      # the file will only be transferred if the destination does not exist
      force: no
      owner: root
      group: root
      mode: '0644'

  - name: Copy provided systemd unit
    copy:
      dest: /etc/systemd/system/caddy.service
      src: ../software/caddy/caddy.service
      # the file will only be transferred if the destination does not exist
      force: no
      owner: root
      group: root
      mode: '0644'
    register: unit_copy_status

  - name: Reload systemd daemon
    systemd:
      daemon_reload: yes
    become: yes
    # run only when a new systemd unit was copied
    when: unit_copy_status.changed

  - name: Restart Caddy service
    systemd:
      name: caddy
      state: restarted
    become: yes
    # run only when a new Debian package was installed
    when: deb_install_status.changed