---
- hosts: all
  vars:
    caddy_version: "2.3.0"
    caddy_checksum: "e86fc81a8c8c543ef9ec7ade089659cacdb573b34594a248ff0fa5d64e0a7b1aa5418d9d90b503b99ea32d3ad3c7427f3d5b9117a9c4941aed3d6fbd0d5f2989"

  tasks:
  - name: Create temporary download directory
    tempfile:
      state: directory
    register: tempdir

  - name: Download Caddy Debian package from official GitHub Page
    get_url:
      # Caddy Debian package for Linux amd64
      url: "https://github.com/caddyserver/caddy/releases/download/v{{ caddy_version }}/caddy_{{ caddy_version }}_linux_amd64.deb"
      dest: "{{ tempdir.path }}/caddy.deb"
      # SHA-512 sum of the Debian package from the cheksums file of the GitHub release page
      checksum: "sha512:{{ caddy_checksum }}"

  - name: Install Caddy Debian package
    apt:
      deb: "{{ tempdir.path }}/caddy.deb"
    become: yes
    register: deb_install_status
    # Execute the task only on Debian-based hosts
    when: ansible_facts['os_family'] == "Debian"

  - name: Remove the temporary directory
    file:
      path: "{{ tempdir.path }}"
      state: absent
    when: tempdir.path is defined

  - name: Create caddy directory, if it does not exist
    file:
      path: /etc/caddy
      state: directory
      owner: root
      group: root
      mode: '0755'
    become: yes

  - name: Copy provided Caddyfile example
    copy:
      dest: /etc/caddy/Caddyfile
      src: ../software/caddy/Caddyfile
      # The file will only be transferred if the destination does not exist
      force: no
      owner: root
      group: root
      mode: '0644'

  - name: Copy provided systemd unit
    copy:
      dest: /etc/systemd/system/caddy.service
      src: ../software/caddy/caddy.service
      # The file will only be transferred if the destination does not exist
      force: no
      owner: root
      group: root
      mode: '0644'
    register: unit_copy_status

  - name: Reload systemd daemon
    systemd:
      daemon_reload: yes
    become: yes
    # Run only when a new systemd unit was copied
    when: unit_copy_status.changed

  - name: Restart Caddy service
    systemd:
      name: caddy
      state: restarted
    become: yes
    # Run only when a new Debian package was installed
    when: deb_install_status.changed