---
- hosts: all
  tasks:
  - name: Create a temporary download directory
    tempfile:
      state: directory
      suffix: temp
    register: tempdir
    when: "ansible_system == 'Linux'"

  - name: Retrieve latest Alacritty terminfo file
    get_url:
      url: https://raw.githubusercontent.com/alacritty/alacritty/master/extra/alacritty.info
      dest: "{{ tempdir.path }}/alacritty.info"
    when:
      - tempdir.path is defined
      - "ansible_system == 'Linux'"

  - name: Install Alacritty terminfo file
    shell: "tic -xe alacritty,alacritty-direct {{ tempdir.path | quote }}/alacritty.info"
    become: yes
    when:
      - tempdir.path is defined
      - "ansible_system == 'Linux'"

  - name: Remove the temporary download directory
    file:
      path: "{{ tempdir.path }}"
      state: absent
    when:
      - tempdir.path is defined
      - "ansible_system == 'Linux'"



  